//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNT.OfficeLabelTool.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SNT.OfficeLabelTool.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get sensitivity label information from a pre-existing Excel, Word or Powerpoint file.
        /// </summary>
        public static string GetSensitivityLabel_Description {
            get {
                return ResourceManager.GetString("GetSensitivityLabel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSensitivityLabel.
        /// </summary>
        public static string GetSensitivityLabel_DisplayName {
            get {
                return ResourceManager.GetString("GetSensitivityLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path of the file you want to retrieve label information from.
        /// </summary>
        public static string GetSensitivityLabel_FilePath_Description {
            get {
                return ResourceManager.GetString("GetSensitivityLabel_FilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePath.
        /// </summary>
        public static string GetSensitivityLabel_FilePath_DisplayName {
            get {
                return ResourceManager.GetString("GetSensitivityLabel_FilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensitivity label ID.
        /// </summary>
        public static string GetSensitivityLabel_LabelId_Description {
            get {
                return ResourceManager.GetString("GetSensitivityLabel_LabelId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelId.
        /// </summary>
        public static string GetSensitivityLabel_LabelId_DisplayName {
            get {
                return ResourceManager.GetString("GetSensitivityLabel_LabelId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of sensitivity level.
        /// </summary>
        public static string GetSensitivityLabel_LabelName_Description {
            get {
                return ResourceManager.GetString("GetSensitivityLabel_LabelName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelName.
        /// </summary>
        public static string GetSensitivityLabel_LabelName_DisplayName {
            get {
                return ResourceManager.GetString("GetSensitivityLabel_LabelName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site ID of sharepoint site.
        /// </summary>
        public static string GetSensitivityLabel_SiteId_Description {
            get {
                return ResourceManager.GetString("GetSensitivityLabel_SiteId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiteId.
        /// </summary>
        public static string GetSensitivityLabel_SiteId_DisplayName {
            get {
                return ResourceManager.GetString("GetSensitivityLabel_SiteId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set sensitivity label to Microsoft Excel, Word or Powerpoint files.
        /// </summary>
        public static string SetSensitivityLabel_Description {
            get {
                return ResourceManager.GetString("SetSensitivityLabel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetSensitivityLabel.
        /// </summary>
        public static string SetSensitivityLabel_DisplayName {
            get {
                return ResourceManager.GetString("SetSensitivityLabel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path of the file you want to set the label to.
        /// </summary>
        public static string SetSensitivityLabel_FilePath_Description {
            get {
                return ResourceManager.GetString("SetSensitivityLabel_FilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePath.
        /// </summary>
        public static string SetSensitivityLabel_FilePath_DisplayName {
            get {
                return ResourceManager.GetString("SetSensitivityLabel_FilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label ID of the sensitivity label.
        /// </summary>
        public static string SetSensitivityLabel_LabelId_Description {
            get {
                return ResourceManager.GetString("SetSensitivityLabel_LabelId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelId.
        /// </summary>
        public static string SetSensitivityLabel_LabelId_DisplayName {
            get {
                return ResourceManager.GetString("SetSensitivityLabel_LabelId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the sensitivity label.
        /// </summary>
        public static string SetSensitivityLabel_LabelName_Description {
            get {
                return ResourceManager.GetString("SetSensitivityLabel_LabelName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelName.
        /// </summary>
        public static string SetSensitivityLabel_LabelName_DisplayName {
            get {
                return ResourceManager.GetString("SetSensitivityLabel_LabelName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of the setting (Bool).
        /// </summary>
        public static string SetSensitivityLabel_Result_Description {
            get {
                return ResourceManager.GetString("SetSensitivityLabel_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string SetSensitivityLabel_Result_DisplayName {
            get {
                return ResourceManager.GetString("SetSensitivityLabel_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site ID of the sharepoint site.
        /// </summary>
        public static string SetSensitivityLabel_SiteId_Description {
            get {
                return ResourceManager.GetString("SetSensitivityLabel_SiteId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiteId.
        /// </summary>
        public static string SetSensitivityLabel_SiteId_DisplayName {
            get {
                return ResourceManager.GetString("SetSensitivityLabel_SiteId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
